// AUTO-GENERATED by scripts/gen-cbam-seed.mjs.
// Demo-mode seed: Hindalco Renukoot CBAM Communication workbook values
// (CY'25), used to pre-populate the report on first open. The SOT-derived
// pre-fill (cbamSOT.ts → sotHydratedState) takes priority over anything in
// this map — cells already covered by the SOT are intentionally absent.

export interface CbamSeedEntry {
  values?: Record<string, string | number | boolean>;
  rows?: Array<Record<string, string | number | boolean>>;
}

export const CBAM_SEED: Record<string, CbamSeedEntry> = {
  "A.1": {
    "values": {
      "start": "2025-01-01",
      "end": "2025-12-31"
    }
  },
  "A.2": {
    "values": {
      "nameEn": "Hindalco Industries Limited (Renukoot)",
      "street": "ADM Building, Renukoot",
      "postcode": "231217",
      "poBox": "P.O.> Renukoot",
      "city": "Sonbhadra",
      "country": "IN — India",
      "unlocode": "IN RKO",
      "lat": 24.22148,
      "lng": 83.03231,
      "repName": "Ali Waris Rao",
      "repEmail": "ali.rao@adityabirla.com",
      "repTel": "+91 22 62610588"
    }
  },
  "A.4": {
    "rows": [
      {
        "good": "Unwrought aluminium",
        "route1": "Primary (electrolytic) smelting",
        "pfcRelevant": true
      },
      {
        "good": "Aluminium products",
        "route1": "All production routes",
        "pfcRelevant": true
      },
      {
        "good": "Aluminium products",
        "route1": "All production routes",
        "pfcRelevant": true
      }
    ]
  },
  "A.5": {
    "rows": [
      {
        "good": "Aluminium products",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Hirakud)"
      },
      {
        "good": "Aluminium products",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Taloja)"
      },
      {
        "good": "Unwrought aluminium",
        "country": "IN — India",
        "route": "Primary (electrolytic) smelting",
        "supplier": "Hindalco Industries Limited (Mahan Aluminium)"
      },
      {
        "good": "Unwrought aluminium",
        "country": "IN — India",
        "route": "Other production routes",
        "supplier": "Hindalco Industries Limited (Allupuram)"
      },
      {
        "good": "Unwrought aluminium",
        "country": "IN — India",
        "route": "Other production routes",
        "supplier": "Hindalco-Almex Aerospace Limited"
      },
      {
        "good": "Unwrought aluminium",
        "country": "IN — India",
        "route": "Secondary melting (recycling)",
        "supplier": "CRM Green Technology"
      }
    ]
  },
  "B.1": {
    "rows": [
      {
        "method": "Combustion",
        "name": "Residual Fuel Oil",
        "adUnit": "t",
        "ncv": 40.4,
        "ef": 77.4,
        "efUnit": "tCO2/TJ",
        "oxF": 100
      },
      {
        "method": "Combustion",
        "name": "Propane",
        "adUnit": "t",
        "ncv": 47.3,
        "ef": 2.997632,
        "efUnit": "tCO2/t",
        "oxF": 100
      },
      {
        "method": "Combustion",
        "name": "LPG",
        "adUnit": "t",
        "ncv": 47.3,
        "ef": 2.939361,
        "efUnit": "tCO2/t",
        "oxF": 100
      },
      {
        "method": "Process emissions",
        "name": "Pre Baked Anode",
        "adUnit": "t",
        "ef": 3.549,
        "efUnit": "tCO2/t"
      }
    ]
  },
  "B.2": {
    "rows": [
      {
        "method": "Slope method",
        "tech": "Legacy Point Feed Pre Baked (PFPBL)",
        "aeFreq": 0.152008,
        "aeDur": 2.059444,
        "slopeCF4": 0.122,
        "slopeC2F6": 0.097
      }
    ]
  },
  "C.3": {
    "values": {
      "quality": "Mostly measurements & international standard factors for e.g. the emission factor",
      "verification": "Internal audits"
    }
  },
  "D.1": {
    "rows": [
      {
        "good": "Unwrought aluminium",
        "prodSecondary": 0,
        "prodOther": 0,
        "prodUnknown": 0,
        "nonCbam": 0,
        "hasHeat": false,
        "hasWasteGas": false,
        "elecSource": "Mix",
        "elecExportedMWh": 0,
        "elecExportedEF": 0
      },
      {
        "good": "Aluminium products",
        "hasHeat": false,
        "hasWasteGas": false,
        "elecSource": "Mix",
        "elecExportedMWh": 0,
        "elecExportedEF": 0
      },
      {
        "good": "Aluminium products",
        "hasHeat": false,
        "hasWasteGas": false,
        "elecSource": "Mix",
        "elecExportedMWh": 0,
        "elecExportedEF": 0
      }
    ]
  },
  "E.1": {
    "rows": [
      {
        "good": "Aluminium products",
        "toUnwrought": 0,
        "toExtrusion": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Hirakud)"
      },
      {
        "good": "Aluminium products",
        "toUnwrought": 0,
        "toExtrusion": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Taloja)"
      },
      {
        "good": "Unwrought aluminium",
        "toUnwrought": 0,
        "toFRP": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Mahan Aluminium)"
      },
      {
        "good": "Unwrought aluminium",
        "toUnwrought": 0,
        "toFRP": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "Hindalco Industries Limited (Allupuram)"
      },
      {
        "good": "Unwrought aluminium",
        "toUnwrought": 0,
        "toFRP": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "Hindalco-Almex Aerospace Limited"
      },
      {
        "good": "Unwrought aluminium",
        "toUnwrought": 0,
        "toFRP": 0,
        "consumedOther": 0,
        "seeDirectSource": "Measured",
        "elecPerTSource": "Measured",
        "elecSource": "Mix",
        "country": "IN — India",
        "supplier": "CRM Green Technology"
      }
    ]
  },
  "summary.1": {
    "rows": [
      {
        "process": "Unwrought Aluminium",
        "good": "Unwrought aluminium",
        "cnCode": "76011010",
        "cnName": "Aluminium slabs, not alloyed, unwrought",
        "productName": "Slab, Ingot",
        "seeDirect": 1.910696,
        "seeIndirect": 15.197636,
        "seeTotal": 17.108332,
        "elecEFSource": "Mix",
        "embeddedElec": 14.295801
      },
      {
        "process": "Flat Rolled Products (FRP)",
        "good": "Aluminium products",
        "cnCode": "76061130",
        "cnName": "Aluminium Composite Panel, of non-alloy aluminium, of a thickness of > 0,2 mm",
        "productName": "FRP",
        "seeDirect": 1.963135,
        "seeIndirect": 16.256968,
        "seeTotal": 18.220103,
        "elecEFSource": "Mix",
        "embeddedElec": 15.221586
      },
      {
        "process": "Flat Rolled Products (FRP)",
        "good": "Aluminium products",
        "cnCode": "76061211",
        "cnName": "Beverage can body stock, of aluminium alloys, of a thickness of > 0,2 mm",
        "productName": "Can stock",
        "seeDirect": 1.963135,
        "seeIndirect": 16.256968,
        "seeTotal": 18.220103,
        "elecEFSource": "Mix",
        "embeddedElec": 15.221586
      },
      {
        "process": "Extrusion Products",
        "good": "Aluminium products",
        "cnCode": "76042990",
        "cnName": "Solid profiles, of aluminium alloys, n.e.s.",
        "productName": "Solid extruded alloy",
        "seeDirect": 1.868011,
        "seeIndirect": 15.862658,
        "seeTotal": 17.730669,
        "elecEFSource": "Mix",
        "embeddedElec": 15.093308
      },
      {
        "process": "Extrusion Products",
        "good": "Aluminium products",
        "cnCode": "76082081",
        "cnName": "Tubes and pipes of aluminium alloys, not further worked than extruded (excl. hollow profiles)",
        "productName": "Hollow extruded profile",
        "seeDirect": 1.868011,
        "seeIndirect": 15.862658,
        "seeTotal": 17.730669,
        "elecEFSource": "Mix",
        "embeddedElec": 15.093308
      },
      {
        "process": "Extrusion Products",
        "good": "Aluminium products",
        "cnCode": "76042910",
        "cnName": "Bars and rods of aluminium alloys",
        "productName": "Solif extruded profile i.e Bar Rods",
        "seeDirect": 1.868011,
        "seeIndirect": 15.862658,
        "seeTotal": 17.730669,
        "elecEFSource": "Mix",
        "embeddedElec": 15.093308
      }
    ]
  },
  "F.1": {
    "values": {
      "hasCHP": true
    }
  }
};

export const CBAM_SEED_VERSION = "2026-05-25-r5";
