// First-run seed for the CBAM questionnaire (/report/cbam).
//
// Populated from CBAM_template_filled.xlsx (CY2024-25 reporting period,
// Hindalco-Renukoot draft).
//
// Loaded by Questionnaire.tsx when localStorage[CBAM_ANSWERS_KEY] is absent.

import type { Answers, SavedAnswer } from "./storage";

const NOW = "2026-04-01T09:00:00.000Z";

function fields(values: Record<string, unknown>): SavedAnswer {
  return { values, rows: [], status: "in-progress", updatedAt: NOW };
}

function table(rows: Record<string, unknown>[]): SavedAnswer {
  return { values: {}, rows, status: "in-progress", updatedAt: NOW };
}

export const cbamSeed: Answers = {
  // ── A. Installation Data ───────────────────────────────────────────────
  "A.1": fields({
    start: "2024-04-01",
    end: "2025-03-31",
  }),
  "A.2": fields({
    nameLocal: "Hindalco Industries Limited - Renukoot",
    nameEn: "Hindalco Industries Limited - Renukoot",
    street: "P.O. Renukoot, Industrial Area",
    economicActivity: "Aluminium smelting and casting",
    postcode: "231217",
    poBox: "",
    city: "Renukoot, Sonbhadra",
    country: "India",
    unlocode: "INRNK",
    lat: 24.215,
    lng: 83.034,
    repName: "Atul Sharma",
    repEmail: "atul.sharma@adityabirla.com",
    repTel: "+91-5446-252101",
  }),
  "A.3": fields({
    verifierCompany: "",
    verifierStreet: "",
    verifierCity: "",
    verifierPostcode: "",
    verifierCountry: "",
    verifierRepName: "",
    verifierRepEmail: "",
    verifierRepTel: "",
    accreditationMS: "",
    accreditationBody: "",
    accreditationRegNo: "",
  }),
  "A.4": table([
    { good: "Unwrought aluminium", route1: "Primary (electrolytic) smelting", route2: null, pfcRelevant: null },
    { good: "Aluminium products", route1: "All production routes", route2: null, pfcRelevant: null },
  ]),
  "A.5": table([]),

  // ── B. Emissions ───────────────────────────────────────────────────────
  "B.1": table([
    {
      name: "Coal (CPP)",
      method: "Combustion",
      ad: 4499139.12,
      adUnit: "t",
      ncv: 16.43,
      ef: 90.6,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 98,
      convF: 100,
      biomass: 0,
    },
    {
      name: "HSD (CPP & Smelter Aux)",
      method: "Combustion",
      ad: 1437.92,
      adUnit: "t",
      ncv: 45.86,
      ef: 73.3,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Biomass - Wood pellets (CPP)",
      method: "Combustion",
      ad: 706.51,
      adUnit: "t",
      ncv: 16,
      ef: 100,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 100,
    },
    {
      name: "Coal (Cogen / CHP)",
      method: "Combustion",
      ad: 651036.59,
      adUnit: "t",
      ncv: 14.61,
      ef: 90.6,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 98,
      convF: 100,
      biomass: 0,
    },
    {
      name: "HSD (Cogen)",
      method: "Combustion",
      ad: 320.94,
      adUnit: "t",
      ncv: 45,
      ef: 73.3,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Biomass Briquettes (Cogen)",
      method: "Combustion",
      ad: 1534.94,
      adUnit: "t",
      ncv: 14.31,
      ef: 100,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 100,
    },
    {
      name: "LSHS / HFO (Anode Bake Furnace)",
      method: "Combustion",
      ad: 13338.49,
      adUnit: "t",
      ncv: 40.4,
      ef: 79.91,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "LSHS / HFO (Cast House)",
      method: "Combustion",
      ad: 12011.72,
      adUnit: "t",
      ncv: 40.4,
      ef: 79.91,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Propane (Cast House)",
      method: "Combustion",
      ad: 637.32,
      adUnit: "t",
      ncv: 46.4,
      ef: 56.1,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "LPG (Cast House)",
      method: "Combustion",
      ad: 22.99,
      adUnit: "t",
      ncv: 47.3,
      ef: 63.1,
      efUnit: "tCO2/TJ",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Net Anode Consumption (Smelter) - Prebake",
      method: "Process emissions",
      ad: 175418.32,
      adUnit: "t",
      ncv: null,
      ef: 3.557,
      efUnit: "tCO2/t",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Pitch Volatiles (Anode Baking)",
      method: "Process emissions",
      ad: 231654.07,
      adUnit: "t",
      ncv: null,
      ef: 0.18162,
      efUnit: "tCO2/t",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Bake Furnace Packing Material (Coke)",
      method: "Process emissions",
      ad: 218644.46,
      adUnit: "t",
      ncv: null,
      ef: 0.05062,
      efUnit: "tCO2/t",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
    {
      name: "Soda Ash (Na2CO3) - Smelter",
      method: "Process emissions",
      ad: 1446.87,
      adUnit: "t",
      ncv: null,
      ef: 0.415,
      efUnit: "tCO2/t",
      cContent: null,
      oxF: 100,
      convF: 100,
      biomass: 0,
    },
  ]),
  "B.2": table([
    {
      method: "Slope method",
      tech: "Centre Worked Pre-Bake (CWPB)",
      tAl: 500000,
      aeFreq: null,
      aeDur: null,
      overvoltage: null,
      slopeCF4: null,
      slopeC2F6: null,
    },
    {
      method: "Slope method",
      tech: "CWPB (Centre Worked Pre-Bake)",
      tAl: 407602.44,
      aeFreq: null,
      aeDur: null,
      overvoltage: null,
      slopeCF4: null,
      slopeC2F6: null,
    },
  ]),
  "B.3": table([
    { name: "N2O", ghg: "N2O", conc: null, flow: null, hours: null },
    { name: "CO2 transfer", ghg: "CO2", conc: null, flow: null, hours: null },
  ]),

  // ── C. Installation-level emissions & energy ────────────────────────────
  "C.1": fields({
    cbamDirect: null,
    electricity: null,
    nonCbam: null,
    rest: null,
  }),
  "C.2": fields({
    co2: null,
    biomass: null,
    n2o: null,
    pfc: null,
    direct: null,
    indirect: 6304777,
  }),
  "C.3": fields({
    quality: "",
    justification: null,
    verification: "",
  }),

  // ── D. Production processes ────────────────────────────────────────────
  "D.1": table([
    {
      good: "Unwrought aluminium",
      output: 407602.44,
      directEm: 782148.15,
      heatProduced: null,
      heatConsumed: null,
      heatImported: null,
      heatExported: null,
      elecMWh: 5884634,
      elecSource: "EF of electricity produced in the installation other than by cogeneration",
      elecEF: 1.063084,
    },
    {
      good: "Aluminium products",
      output: 113624,
      directEm: 4333,
      heatProduced: null,
      heatConsumed: null,
      heatImported: null,
      heatExported: null,
      elecMWh: 93408,
      elecSource: "EF of electricity produced in the installation other than by cogeneration",
      elecEF: 1.063084,
    },
  ]),

  // ── E. Purchased precursors (none reported) ────────────────────────────
  "E.1": table([]),

  // ── F. Tools (CHP & carbon price) ──────────────────────────────────────
  "F.1": fields({
    hasCHP: null,
    fuelIn: null,
    heatOut: null,
    elecOut: null,
    allocationHeat: null,
  }),
  "F.2": fields({
    priceType: "",
    rebateType: "",
    currency: "",
    pricePerTon: null,
    amountDue: null,
    notes: "",
  }),

  // ── G. Notes ──────────────────────────────────────────────────────────
  "G.1": fields({
    notes: "",
  }),

  // ── SP. Summary — Products by CN code ─────────────────────────────────
  "SP.1": table([
    {
      cnCode: "7601 10 90 — Aluminium, not alloyed, unwrought (excl. slabs)",
      productName: "Aluminium, not alloyed, unwrought (excl. slabs)",
      process: "P1",
      seeDirect: 6.13829928143419,
      seeIndirect: 49.8842347757473,
      seeTotal: 56.0225340571815,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
    {
      cnCode: "7601 20 40 — Unwrought aluminium alloys in the form of billets",
      productName: "Unwrought aluminium alloys in the form of billets",
      process: "P1",
      seeDirect: 6.13829928143419,
      seeIndirect: 49.8842347757473,
      seeTotal: 56.0225340571815,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
    {
      cnCode: "7601 20 80 — Unwrought aluminium alloys (excl. slabs and billets)",
      productName: "Unwrought aluminium alloys (excl. slabs and billets)",
      process: "P1",
      seeDirect: 6.13829928143419,
      seeIndirect: 49.8842347757473,
      seeTotal: 56.0225340571815,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
    {
      cnCode: "7605 11 00 — Wire of non-alloy aluminium, max cross-section > 7 mm",
      productName: "Wire of non-alloy aluminium, with a maximum cross-sectional dimension of > 7 mm",
      process: "P1",
      seeDirect: 6.13829928143419,
      seeIndirect: 49.8842347757473,
      seeTotal: 56.0225340571815,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
    {
      cnCode: "7606 12 30 — Aluminium Composite Panel, of aluminium alloys, thickness > 0.2 mm",
      productName: "Aluminium Composite Panel, of aluminium alloys, of a thickness of > 0,2 mm",
      process: "P2",
      seeDirect: 9.65810242240678,
      seeIndirect: 79.0527177819728,
      seeTotal: 88.7108202043796,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
    {
      cnCode: "7604 29 10 — Bars and rods of aluminium alloys",
      productName: "Bars and rods of aluminium alloys",
      process: "P2",
      seeDirect: 9.65810242240678,
      seeIndirect: 79.0527177819728,
      seeTotal: 88.7108202043796,
      defaultsShare: 0,
      scrapPerT: null,
      nonAlPct: null,
      preScrapPct: null,
    },
  ]),

  // ── SC. Summary — Communication to declarant ─────────────────────────
  "SC.1": fields({
    installationName: "Hindalco Industries Limited - Renukoot",
    country: "India",
    unlocode: "INRNK",
    reportingStart: "2024-04-01",
    reportingEnd: "2025-03-31",
  }),
  "SC.2": fields({
    calc: null,
    pfc: null,
    measured: null,
    other: null,
  }),
  "SC.3": fields({
    instrument: "",
    additional: "",
  }),
};
