// Parses an uploaded STANDARD template and returns it for review before commit.
//
//   POST /api/esg/entry/import/standard-preview   (multipart: file)
//
// Sibling of import/preview, which handles the client's OWN monthly forms by
// fuzzy label match. This route reads our own template by explicit parameter
// key, so there is no match confidence to display and no unmatched-label
// guesswork to review — only the values themselves, the override warning, and
// whatever validation flags the figures raise.
//
// Nothing is written to input_value here. The rows are recorded as an
// import_batch in 'preview' state so the commit step has something to consume
// and the logbook can show that an upload happened even if nobody committed it.

import { NextRequest } from "next/server";

import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { parseStandardTemplate } from "@/lib/standardTemplate/parseTemplate";
import { SOURCE_LABEL_SEP } from "@/lib/standardTemplate/templateLayout";
import { resolveTarget, resolveRows } from "@/lib/standardTemplate/standardService";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "no-store, no-cache, must-revalidate",
    },
  });
}

export async function POST(req: NextRequest): Promise<Response> {
  let file: File | null = null;
  let overrideSite: string | undefined;
  let overrideFy: string | undefined;
  let overrideMonth: number | undefined;

  try {
    const form = await req.formData();
    const f = form.get("file");
    if (f instanceof File) file = f;
    const s = form.get("siteCode");
    if (typeof s === "string" && s) overrideSite = s;
    const fy = form.get("fiscalYear");
    if (typeof fy === "string" && fy) overrideFy = fy;
    const m = form.get("monthNo");
    if (typeof m === "string" && m) overrideMonth = Number(m);
  } catch {
    return json({ ok: false, error: "Expected a multipart upload with a 'file' field." }, 400);
  }

  if (!file) return json({ ok: false, error: "No file was uploaded." }, 400);

  try {
    const buffer = Buffer.from(await file.arrayBuffer());
    const parsed = await parseStandardTemplate(buffer);

    if (!parsed.ok || !parsed.rows || !parsed.header) {
      return json(
        { ok: false, error: parsed.error ?? "The file could not be read.", versionFound: parsed.versionFound },
        422
      );
    }

    const resolved = await resolveTarget(parsed.header, {
      siteCode: overrideSite,
      fiscalYear: overrideFy,
      monthNo: overrideMonth,
    });
    if (!resolved.ok) return json({ ok: false, error: resolved.error }, 422);
    const { site, period } = resolved.target;

    const { values, unknownKeys, labelsByKey } = await resolveRows(parsed.rows);

    if (values.size === 0) {
      return json(
        {
          ok: false,
          error:
            unknownKeys.length > 0
              ? `None of the ${unknownKeys.length} parameter keys in this file are ` +
                `recognised. It may have been generated by a different deployment.`
              : "The template was read but every row was left blank.",
          unknownKeys,
        },
        422
      );
    }

    // ---- Record the upload -------------------------------------------------
    const { data: batch, error: batchErr } = await supabaseAdmin
      .from("import_batch")
      .insert({
        site_id: site.id,
        period_id: period.id,
        filename: file.name,
        sheet_name: "Return",
        status: "preview",
        uploaded_by: "esg-team",
        row_count: parsed.rows.length,
        matched_count: values.size,
        unmatched_count: unknownKeys.length,
        // import_batch has no column distinguishing the two upload paths, and
        // adding one would be a migration for a label. The note carries it, and
        // the logbook already shows notes.
        note: `Standard template v${parsed.templateVersion}`,
      })
      .select("id")
      .single();
    if (batchErr) throw batchErr;
    const batchId = batch.id as number;

    // One row per parsed cell, so the audit trail survives even for rows the
    // commit step later drops. matched_field_id stays NULL: no site_form_field
    // claims these rows, and pretending otherwise would corrupt the join the
    // other path relies on. The key goes in source_label instead, so the trail
    // is readable without a join.
    const batchRows = parsed.rows
      .filter((r) => values.has(r.key) || unknownKeys.includes(r.key))
      .map((r) => ({
        batch_id: batchId,
        sheet_cell: r.cell,
        source_label: `${r.key}${
          labelsByKey[r.key] ? `${SOURCE_LABEL_SEP}${labelsByKey[r.key]}` : ""
        }`,
        raw_text: r.rawText,
        matched_field_id: null,
        match_confidence: values.has(r.key) ? "exact" : "unmatched",
        parsed_value: r.value,
        unit_factor: 1,
        canonical_value: r.value,
        is_not_available: r.isNotAvailable,
      }));

    if (batchRows.length) {
      const { error: rowsErr } = await supabaseAdmin
        .from("import_batch_row")
        .insert(batchRows);
      if (rowsErr) throw rowsErr;
    }

    // ---- Existing data, so the UI can warn before committing --------------
    const { data: existing } = await supabaseAdmin
      .from("input_value")
      .select("parameter_id, value_num, is_not_available")
      .eq("site_id", site.id)
      .eq("period_id", period.id)
      .is("superseded_at", null);

    const { data: sub } = await supabaseAdmin
      .from("site_submission")
      .select("status, entered_by, updated_at")
      .eq("site_id", site.id)
      .eq("period_id", period.id)
      .maybeSingle();

    const rows = parsed.rows
      .filter((r) => values.has(r.key))
      .map((r) => ({
        key: r.key,
        label: labelsByKey[r.key] ?? r.label ?? r.key,
        cell: r.cell,
        rawText: r.rawText,
        value: r.value,
        isNotAvailable: r.isNotAvailable,
        remarks: r.remarks,
        parseNote: r.parseNote,
        detectedUnit: r.detectedUnit,
      }));

    return json({
      ok: true,
      batchId,
      filename: file.name,
      templateVersion: parsed.templateVersion,
      site: { code: site.code, name: site.name },
      period: {
        fiscalYear: period.fiscalYear,
        monthNo: period.monthNo,
        monthLabel: period.monthLabel,
      },
      rows,
      unknownKeys,
      summary: {
        matched: rows.length,
        unknown: unknownKeys.length,
        notAvailable: rows.filter((r) => r.isNotAvailable).length,
        reportedZero: rows.filter((r) => r.value === 0).length,
        blank: parsed.blankCount ?? 0,
      },
      existing: existing?.length
        ? {
            valueCount: existing.length,
            status: sub?.status ?? "draft",
            lastEnteredBy: (sub?.entered_by as string | null) ?? null,
            lastUpdatedAt: (sub?.updated_at as string | null) ?? null,
          }
        : null,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[entry/import/standard-preview] failed", { message });
    return json({ ok: false, error: message }, 500);
  }
}
