-- =============================================================================
-- BIRLA ESTATES — HR & PROCUREMENT MONTHLY RETURN INPUT PARAMETERS
--
-- GENERATED FILE — do not edit by hand. Regenerate with:
--   npx tsx scripts/gen-hr-proc-seed.ts
--
-- One input_parameter per data cell of the two monthly workbooks ("BRSR - HR"
-- and "BRSR - Procurement"), as declared in src/lib/hrProcReturn/. The sheets
-- are filled CUMULATIVELY (each month carries FY-to-date figures), values are
-- booked against the GROUP site at month periods, and the export takes the
-- latest month per parameter. Cells the template computes with its own
-- formulas are deliberately absent.
--
-- Apply after 16_dashboard_presets.sql.
-- =============================================================================

set search_path = esg, public;

-- Two new domains; the lookup table is extended by insert (SCOPE3 precedent).
insert into esg.domain (code, name, sort_order) values
    ('HR', 'Human Resources & People', 90),
    ('PROCUREMENT', 'Procurement, Supply Chain & Marketing', 95)
on conflict (code) do nothing;

-- input_value_history predates text values; commitValues archives value_text
-- on supersession from now on, so history must be able to hold it.
alter table esg.input_value_history add column if not exists value_text text;


-- -----------------------------------------------------------------------------
-- BRSR - HR (sheet "HR") — 253 parameters
-- -----------------------------------------------------------------------------
insert into esg.input_parameter (key, domain, section, label, unit, value_type, is_memo, sort_order, notes) values
('hr.headcount_perm_emp_m', 'HR', 'headcount', 'Male permanent employees', 'count', 'number', false, 10, 'Template cell HR!C4'),
('hr.headcount_perm_emp_f', 'HR', 'headcount', 'Female permanent employees', 'count', 'number', false, 20, 'Template cell HR!D4'),
('hr.headcount_oth_emp_m', 'HR', 'headcount', 'Male other than permanent employees', 'count', 'number', false, 30, 'Template cell HR!C5'),
('hr.headcount_oth_emp_f', 'HR', 'headcount', 'Female other than permanent employees', 'count', 'number', false, 40, 'Template cell HR!D5'),
('hr.headcount_perm_wkr_m', 'HR', 'headcount', 'Male permanent workers', 'count', 'number', false, 50, 'Template cell HR!C6'),
('hr.headcount_perm_wkr_f', 'HR', 'headcount', 'Female permanent workers', 'count', 'number', false, 60, 'Template cell HR!D6'),
('hr.headcount_oth_wkr_m', 'HR', 'headcount', 'Male other than permanent workers', 'count', 'number', false, 70, 'Template cell HR!C7'),
('hr.headcount_oth_wkr_f', 'HR', 'headcount', 'Female other than permanent workers', 'count', 'number', false, 80, 'Template cell HR!D7'),
('hr.pwd_perm_emp_m', 'HR', 'pwd', 'Differently abled male permanent employees', 'count', 'number', false, 90, 'Template cell HR!C10'),
('hr.pwd_perm_emp_f', 'HR', 'pwd', 'Differently abled female permanent employees', 'count', 'number', false, 100, 'Template cell HR!D10'),
('hr.pwd_oth_emp_m', 'HR', 'pwd', 'Differently abled male other than permanent employees', 'count', 'number', false, 110, 'Template cell HR!C11'),
('hr.pwd_oth_emp_f', 'HR', 'pwd', 'Differently abled female other than permanent employees', 'count', 'number', false, 120, 'Template cell HR!D11'),
('hr.pwd_perm_wkr_m', 'HR', 'pwd', 'Differently abled male permanent workers', 'count', 'number', false, 130, 'Template cell HR!C12'),
('hr.pwd_perm_wkr_f', 'HR', 'pwd', 'Differently abled female permanent workers', 'count', 'number', false, 140, 'Template cell HR!D12'),
('hr.pwd_oth_wkr_m', 'HR', 'pwd', 'Differently abled male other than permanent workers', 'count', 'number', false, 150, 'Template cell HR!C13'),
('hr.pwd_oth_wkr_f', 'HR', 'pwd', 'Differently abled female other than permanent workers', 'count', 'number', false, 160, 'Template cell HR!D13'),
('hr.eoy_perm_emp_u30_m', 'HR', 'count_eoy', 'permanent employees at end of FY: males below 30', 'count', 'number', false, 170, 'Template cell HR!C17'),
('hr.eoy_perm_emp_u30_f', 'HR', 'count_eoy', 'permanent employees at end of FY: females below 30', 'count', 'number', false, 180, 'Template cell HR!D17'),
('hr.eoy_perm_emp_30_50_m', 'HR', 'count_eoy', 'permanent employees at end of FY: males 30-50', 'count', 'number', false, 190, 'Template cell HR!E17'),
('hr.eoy_perm_emp_30_50_f', 'HR', 'count_eoy', 'permanent employees at end of FY: females 30-50', 'count', 'number', false, 200, 'Template cell HR!F17'),
('hr.eoy_perm_emp_o50_m', 'HR', 'count_eoy', 'permanent employees at end of FY: males above 50', 'count', 'number', false, 210, 'Template cell HR!G17'),
('hr.eoy_perm_emp_o50_f', 'HR', 'count_eoy', 'permanent employees at end of FY: females above 50', 'count', 'number', false, 220, 'Template cell HR!H17'),
('hr.eoy_oth_emp_u30_m', 'HR', 'count_eoy', 'other than permanent employees at end of FY: males below 30', 'count', 'number', false, 230, 'Template cell HR!C18'),
('hr.eoy_oth_emp_u30_f', 'HR', 'count_eoy', 'other than permanent employees at end of FY: females below 30', 'count', 'number', false, 240, 'Template cell HR!D18'),
('hr.eoy_oth_emp_30_50_m', 'HR', 'count_eoy', 'other than permanent employees at end of FY: males 30-50', 'count', 'number', false, 250, 'Template cell HR!E18'),
('hr.eoy_oth_emp_30_50_f', 'HR', 'count_eoy', 'other than permanent employees at end of FY: females 30-50', 'count', 'number', false, 260, 'Template cell HR!F18'),
('hr.eoy_oth_emp_o50_m', 'HR', 'count_eoy', 'other than permanent employees at end of FY: males above 50', 'count', 'number', false, 270, 'Template cell HR!G18'),
('hr.eoy_oth_emp_o50_f', 'HR', 'count_eoy', 'other than permanent employees at end of FY: females above 50', 'count', 'number', false, 280, 'Template cell HR!H18'),
('hr.eoy_perm_wkr_u30_m', 'HR', 'count_eoy', 'permanent workers at end of FY: males below 30', 'count', 'number', false, 290, 'Template cell HR!C19'),
('hr.eoy_perm_wkr_u30_f', 'HR', 'count_eoy', 'permanent workers at end of FY: females below 30', 'count', 'number', false, 300, 'Template cell HR!D19'),
('hr.eoy_perm_wkr_30_50_m', 'HR', 'count_eoy', 'permanent workers at end of FY: males 30-50', 'count', 'number', false, 310, 'Template cell HR!E19'),
('hr.eoy_perm_wkr_30_50_f', 'HR', 'count_eoy', 'permanent workers at end of FY: females 30-50', 'count', 'number', false, 320, 'Template cell HR!F19'),
('hr.eoy_perm_wkr_o50_m', 'HR', 'count_eoy', 'permanent workers at end of FY: males above 50', 'count', 'number', false, 330, 'Template cell HR!G19'),
('hr.eoy_perm_wkr_o50_f', 'HR', 'count_eoy', 'permanent workers at end of FY: females above 50', 'count', 'number', false, 340, 'Template cell HR!H19'),
('hr.eoy_oth_wkr_u30_m', 'HR', 'count_eoy', 'other than permanent workers at end of FY: males below 30', 'count', 'number', false, 350, 'Template cell HR!C20'),
('hr.eoy_oth_wkr_u30_f', 'HR', 'count_eoy', 'other than permanent workers at end of FY: females below 30', 'count', 'number', false, 360, 'Template cell HR!D20'),
('hr.eoy_oth_wkr_30_50_m', 'HR', 'count_eoy', 'other than permanent workers at end of FY: males 30-50', 'count', 'number', false, 370, 'Template cell HR!E20'),
('hr.eoy_oth_wkr_30_50_f', 'HR', 'count_eoy', 'other than permanent workers at end of FY: females 30-50', 'count', 'number', false, 380, 'Template cell HR!F20'),
('hr.eoy_oth_wkr_o50_m', 'HR', 'count_eoy', 'other than permanent workers at end of FY: males above 50', 'count', 'number', false, 390, 'Template cell HR!G20'),
('hr.eoy_oth_wkr_o50_f', 'HR', 'count_eoy', 'other than permanent workers at end of FY: females above 50', 'count', 'number', false, 400, 'Template cell HR!H20'),
('hr.boy_perm_emp_u30_m', 'HR', 'count_boy', 'permanent employees at beginning of FY: males below 30', 'count', 'number', false, 410, 'Template cell HR!C26'),
('hr.boy_perm_emp_u30_f', 'HR', 'count_boy', 'permanent employees at beginning of FY: females below 30', 'count', 'number', false, 420, 'Template cell HR!D26'),
('hr.boy_perm_emp_30_50_m', 'HR', 'count_boy', 'permanent employees at beginning of FY: males 30-50', 'count', 'number', false, 430, 'Template cell HR!E26'),
('hr.boy_perm_emp_30_50_f', 'HR', 'count_boy', 'permanent employees at beginning of FY: females 30-50', 'count', 'number', false, 440, 'Template cell HR!F26'),
('hr.boy_perm_emp_o50_m', 'HR', 'count_boy', 'permanent employees at beginning of FY: males above 50', 'count', 'number', false, 450, 'Template cell HR!G26'),
('hr.boy_perm_emp_o50_f', 'HR', 'count_boy', 'permanent employees at beginning of FY: females above 50', 'count', 'number', false, 460, 'Template cell HR!H26'),
('hr.boy_oth_emp_u30_m', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: males below 30', 'count', 'number', false, 470, 'Template cell HR!C27'),
('hr.boy_oth_emp_u30_f', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: females below 30', 'count', 'number', false, 480, 'Template cell HR!D27'),
('hr.boy_oth_emp_30_50_m', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: males 30-50', 'count', 'number', false, 490, 'Template cell HR!E27'),
('hr.boy_oth_emp_30_50_f', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: females 30-50', 'count', 'number', false, 500, 'Template cell HR!F27'),
('hr.boy_oth_emp_o50_m', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: males above 50', 'count', 'number', false, 510, 'Template cell HR!G27'),
('hr.boy_oth_emp_o50_f', 'HR', 'count_boy', 'other than permanent employees at beginning of FY: females above 50', 'count', 'number', false, 520, 'Template cell HR!H27'),
('hr.boy_perm_wkr_u30_m', 'HR', 'count_boy', 'permanent workers at beginning of FY: males below 30', 'count', 'number', false, 530, 'Template cell HR!C28'),
('hr.boy_perm_wkr_u30_f', 'HR', 'count_boy', 'permanent workers at beginning of FY: females below 30', 'count', 'number', false, 540, 'Template cell HR!D28'),
('hr.boy_perm_wkr_30_50_m', 'HR', 'count_boy', 'permanent workers at beginning of FY: males 30-50', 'count', 'number', false, 550, 'Template cell HR!E28'),
('hr.boy_perm_wkr_30_50_f', 'HR', 'count_boy', 'permanent workers at beginning of FY: females 30-50', 'count', 'number', false, 560, 'Template cell HR!F28'),
('hr.boy_perm_wkr_o50_m', 'HR', 'count_boy', 'permanent workers at beginning of FY: males above 50', 'count', 'number', false, 570, 'Template cell HR!G28'),
('hr.boy_perm_wkr_o50_f', 'HR', 'count_boy', 'permanent workers at beginning of FY: females above 50', 'count', 'number', false, 580, 'Template cell HR!H28'),
('hr.boy_oth_wkr_u30_m', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: males below 30', 'count', 'number', false, 590, 'Template cell HR!C29'),
('hr.boy_oth_wkr_u30_f', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: females below 30', 'count', 'number', false, 600, 'Template cell HR!D29'),
('hr.boy_oth_wkr_30_50_m', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: males 30-50', 'count', 'number', false, 610, 'Template cell HR!E29'),
('hr.boy_oth_wkr_30_50_f', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: females 30-50', 'count', 'number', false, 620, 'Template cell HR!F29'),
('hr.boy_oth_wkr_o50_m', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: males above 50', 'count', 'number', false, 630, 'Template cell HR!G29'),
('hr.boy_oth_wkr_o50_f', 'HR', 'count_boy', 'other than permanent workers at beginning of FY: females above 50', 'count', 'number', false, 640, 'Template cell HR!H29'),
('hr.sep_perm_emp_u30_m', 'HR', 'sep_emp', 'Permanent employees separated in FY: males below 30', 'count', 'number', false, 650, 'Template cell HR!C35'),
('hr.sep_perm_wkr_u30_m', 'HR', 'sep_wkr', 'Permanent workers separated in FY: males below 30', 'count', 'number', false, 660, 'Template cell HR!C40'),
('hr.sep_perm_emp_u30_f', 'HR', 'sep_emp', 'Permanent employees separated in FY: females below 30', 'count', 'number', false, 670, 'Template cell HR!D35'),
('hr.sep_perm_wkr_u30_f', 'HR', 'sep_wkr', 'Permanent workers separated in FY: females below 30', 'count', 'number', false, 680, 'Template cell HR!D40'),
('hr.sep_perm_emp_30_50_m', 'HR', 'sep_emp', 'Permanent employees separated in FY: males 30-50', 'count', 'number', false, 690, 'Template cell HR!E35'),
('hr.sep_perm_wkr_30_50_m', 'HR', 'sep_wkr', 'Permanent workers separated in FY: males 30-50', 'count', 'number', false, 700, 'Template cell HR!E40'),
('hr.sep_perm_emp_30_50_f', 'HR', 'sep_emp', 'Permanent employees separated in FY: females 30-50', 'count', 'number', false, 710, 'Template cell HR!F35'),
('hr.sep_perm_wkr_30_50_f', 'HR', 'sep_wkr', 'Permanent workers separated in FY: females 30-50', 'count', 'number', false, 720, 'Template cell HR!F40'),
('hr.sep_perm_emp_o50_m', 'HR', 'sep_emp', 'Permanent employees separated in FY: males above 50', 'count', 'number', false, 730, 'Template cell HR!G35'),
('hr.sep_perm_wkr_o50_m', 'HR', 'sep_wkr', 'Permanent workers separated in FY: males above 50', 'count', 'number', false, 740, 'Template cell HR!G40'),
('hr.sep_perm_emp_o50_f', 'HR', 'sep_emp', 'Permanent employees separated in FY: females above 50', 'count', 'number', false, 750, 'Template cell HR!H35'),
('hr.sep_perm_wkr_o50_f', 'HR', 'sep_wkr', 'Permanent workers separated in FY: females above 50', 'count', 'number', false, 760, 'Template cell HR!H40'),
('hr.sep_region_perm_emp_local', 'HR', 'sep_region', 'Local separations: permanent employees', 'count', 'number', false, 770, 'Template cell HR!C44'),
('hr.sep_region_perm_emp_nonlocal', 'HR', 'sep_region', 'Non-local separations: permanent employees', 'count', 'number', false, 780, 'Template cell HR!D44'),
('hr.sep_region_perm_wkr_local', 'HR', 'sep_region', 'Local separations: permanent workers', 'count', 'number', false, 790, 'Template cell HR!C45'),
('hr.sep_region_perm_wkr_nonlocal', 'HR', 'sep_region', 'Non-local separations: permanent workers', 'count', 'number', false, 800, 'Template cell HR!D45'),
('hr.hires_perm_emp_u30_m', 'HR', 'hires_emp', 'New hires, permanent employees: males below 30', 'count', 'number', false, 810, 'Template cell HR!C50'),
('hr.hires_perm_emp_u30_f', 'HR', 'hires_emp', 'New hires, permanent employees: females below 30', 'count', 'number', false, 820, 'Template cell HR!D50'),
('hr.hires_perm_emp_30_50_m', 'HR', 'hires_emp', 'New hires, permanent employees: males 30-50', 'count', 'number', false, 830, 'Template cell HR!E50'),
('hr.hires_perm_emp_30_50_f', 'HR', 'hires_emp', 'New hires, permanent employees: females 30-50', 'count', 'number', false, 840, 'Template cell HR!F50'),
('hr.hires_perm_emp_o50_m', 'HR', 'hires_emp', 'New hires, permanent employees: males above 50', 'count', 'number', false, 850, 'Template cell HR!G50'),
('hr.hires_perm_emp_o50_f', 'HR', 'hires_emp', 'New hires, permanent employees: females above 50', 'count', 'number', false, 860, 'Template cell HR!H50'),
('hr.hires_oth_emp_u30_m', 'HR', 'hires_emp', 'New hires, other than permanent employees: males below 30', 'count', 'number', false, 870, 'Template cell HR!C51'),
('hr.hires_oth_emp_u30_f', 'HR', 'hires_emp', 'New hires, other than permanent employees: females below 30', 'count', 'number', false, 880, 'Template cell HR!D51'),
('hr.hires_oth_emp_30_50_m', 'HR', 'hires_emp', 'New hires, other than permanent employees: males 30-50', 'count', 'number', false, 890, 'Template cell HR!E51'),
('hr.hires_oth_emp_30_50_f', 'HR', 'hires_emp', 'New hires, other than permanent employees: females 30-50', 'count', 'number', false, 900, 'Template cell HR!F51'),
('hr.hires_oth_emp_o50_m', 'HR', 'hires_emp', 'New hires, other than permanent employees: males above 50', 'count', 'number', false, 910, 'Template cell HR!G51'),
('hr.hires_oth_emp_o50_f', 'HR', 'hires_emp', 'New hires, other than permanent employees: females above 50', 'count', 'number', false, 920, 'Template cell HR!H51'),
('hr.hires_perm_wkr_u30_m', 'HR', 'hires_wkr', 'New hires, permanent workers: males below 30', 'count', 'number', false, 930, 'Template cell HR!C57'),
('hr.hires_perm_wkr_u30_f', 'HR', 'hires_wkr', 'New hires, permanent workers: females below 30', 'count', 'number', false, 940, 'Template cell HR!D57'),
('hr.hires_perm_wkr_30_50_m', 'HR', 'hires_wkr', 'New hires, permanent workers: males 30-50', 'count', 'number', false, 950, 'Template cell HR!E57'),
('hr.hires_perm_wkr_30_50_f', 'HR', 'hires_wkr', 'New hires, permanent workers: females 30-50', 'count', 'number', false, 960, 'Template cell HR!F57'),
('hr.hires_perm_wkr_o50_m', 'HR', 'hires_wkr', 'New hires, permanent workers: males above 50', 'count', 'number', false, 970, 'Template cell HR!G57'),
('hr.hires_perm_wkr_o50_f', 'HR', 'hires_wkr', 'New hires, permanent workers: females above 50', 'count', 'number', false, 980, 'Template cell HR!H57'),
('hr.hires_oth_wkr_u30_m', 'HR', 'hires_wkr', 'New hires, other than permanent workers: males below 30', 'count', 'number', false, 990, 'Template cell HR!C58'),
('hr.hires_oth_wkr_u30_f', 'HR', 'hires_wkr', 'New hires, other than permanent workers: females below 30', 'count', 'number', false, 1000, 'Template cell HR!D58'),
('hr.hires_oth_wkr_30_50_m', 'HR', 'hires_wkr', 'New hires, other than permanent workers: males 30-50', 'count', 'number', false, 1010, 'Template cell HR!E58'),
('hr.hires_oth_wkr_30_50_f', 'HR', 'hires_wkr', 'New hires, other than permanent workers: females 30-50', 'count', 'number', false, 1020, 'Template cell HR!F58'),
('hr.hires_oth_wkr_o50_m', 'HR', 'hires_wkr', 'New hires, other than permanent workers: males above 50', 'count', 'number', false, 1030, 'Template cell HR!G58'),
('hr.hires_oth_wkr_o50_f', 'HR', 'hires_wkr', 'New hires, other than permanent workers: females above 50', 'count', 'number', false, 1040, 'Template cell HR!H58'),
('hr.hires_region_perm_emp_local', 'HR', 'hires_region', 'Local new hires: permanent employees', 'count', 'number', false, 1050, 'Template cell HR!C63'),
('hr.hires_region_perm_emp_nonlocal', 'HR', 'hires_region', 'Non-local new hires: permanent employees', 'count', 'number', false, 1060, 'Template cell HR!D63'),
('hr.hires_region_perm_wkr_local', 'HR', 'hires_region', 'Local new hires: permanent workers', 'count', 'number', false, 1070, 'Template cell HR!C64'),
('hr.hires_region_perm_wkr_nonlocal', 'HR', 'hires_region', 'Non-local new hires: permanent workers', 'count', 'number', false, 1080, 'Template cell HR!D64'),
('hr.senior_mgmt_m', 'HR', 'senior_mgmt', 'Senior management: male', 'count', 'number', false, 1090, 'Template cell HR!C71'),
('hr.senior_mgmt_f', 'HR', 'senior_mgmt', 'Senior management: female', 'count', 'number', false, 1100, 'Template cell HR!D71'),
('hr.senior_mgmt_local_m', 'HR', 'senior_mgmt', 'Senior management hired locally: male', 'count', 'number', false, 1110, 'Template cell HR!C72'),
('hr.senior_mgmt_local_f', 'HR', 'senior_mgmt', 'Senior management hired locally: female', 'count', 'number', false, 1120, 'Template cell HR!D72'),
('hr.ngrbc_emp_programmes', 'HR', 'ngrbc', 'NGRBC awareness programmes held for employees', 'count', 'number', false, 1130, 'Template cell HR!C77'),
('hr.ngrbc_emp_topics', 'HR', 'ngrbc', 'NGRBC topics/principles covered (employees)', null, 'text', false, 1140, 'Template cell HR!D77'),
('hr.ngrbc_emp_covered', 'HR', 'ngrbc', 'Employees covered by NGRBC awareness programmes', 'count', 'number', false, 1150, 'Template cell HR!E77'),
('hr.ngrbc_wkr_programmes', 'HR', 'ngrbc', 'NGRBC awareness programmes held for workers', 'count', 'number', false, 1160, 'Template cell HR!C78'),
('hr.ngrbc_wkr_topics', 'HR', 'ngrbc', 'NGRBC topics/principles covered (workers)', null, 'text', false, 1170, 'Template cell HR!D78'),
('hr.ngrbc_wkr_covered', 'HR', 'ngrbc', 'Workers covered by NGRBC awareness programmes', 'count', 'number', false, 1180, 'Template cell HR!E78'),
('hr.trained_skill_perm_emp_m', 'HR', 'training_skill', 'Permanent male employees trained on skill upgradation', 'count', 'number', false, 1190, 'Template cell HR!C85'),
('hr.trained_skill_perm_emp_f', 'HR', 'training_skill', 'Permanent female employees trained on skill upgradation', 'count', 'number', false, 1200, 'Template cell HR!C86'),
('hr.trained_skill_perm_wkr_m', 'HR', 'training_skill', 'Permanent male workers trained on skill upgradation', 'count', 'number', false, 1210, 'Template cell HR!C89'),
('hr.trained_skill_perm_wkr_f', 'HR', 'training_skill', 'Permanent female workers trained on skill upgradation', 'count', 'number', false, 1220, 'Template cell HR!C90'),
('hr.trained_rights_emp_perm', 'HR', 'training_rights', 'Permanent employees trained on human rights', 'count', 'number', false, 1230, 'Template cell HR!C97'),
('hr.trained_rights_emp_oth', 'HR', 'training_rights', 'Other-than-permanent employees trained on human rights', 'count', 'number', false, 1240, 'Template cell HR!C98'),
('hr.trained_rights_wkr_perm', 'HR', 'training_rights', 'Permanent workers trained on human rights', 'count', 'number', false, 1250, 'Template cell HR!C101'),
('hr.trained_rights_wkr_oth', 'HR', 'training_rights', 'Other-than-permanent workers trained on human rights', 'count', 'number', false, 1260, 'Template cell HR!C102'),
('hr.wellbeing_perm_emp_m_health', 'HR', 'wellbeing', 'Permanent male employees covered by health insurance', 'count', 'number', false, 1270, 'Template cell HR!C106'),
('hr.wellbeing_perm_emp_m_accident', 'HR', 'wellbeing', 'Permanent male employees covered by accident insurance', 'count', 'number', false, 1280, 'Template cell HR!D106'),
('hr.wellbeing_perm_emp_m_parental', 'HR', 'wellbeing', 'Permanent male employees covered by maternity/paternity benefits', 'count', 'number', false, 1290, 'Template cell HR!E106'),
('hr.wellbeing_perm_emp_m_daycare', 'HR', 'wellbeing', 'Permanent male employees covered by daycare facilities', 'count', 'number', false, 1300, 'Template cell HR!F106'),
('hr.wellbeing_perm_emp_f_health', 'HR', 'wellbeing', 'Permanent female employees covered by health insurance', 'count', 'number', false, 1310, 'Template cell HR!C107'),
('hr.wellbeing_perm_emp_f_accident', 'HR', 'wellbeing', 'Permanent female employees covered by accident insurance', 'count', 'number', false, 1320, 'Template cell HR!D107'),
('hr.wellbeing_perm_emp_f_parental', 'HR', 'wellbeing', 'Permanent female employees covered by maternity/paternity benefits', 'count', 'number', false, 1330, 'Template cell HR!E107'),
('hr.wellbeing_perm_emp_f_daycare', 'HR', 'wellbeing', 'Permanent female employees covered by daycare facilities', 'count', 'number', false, 1340, 'Template cell HR!F107'),
('hr.wellbeing_oth_emp_m_health', 'HR', 'wellbeing', 'Other-than-permanent male employees covered by health insurance', 'count', 'number', false, 1350, 'Template cell HR!C109'),
('hr.wellbeing_oth_emp_m_accident', 'HR', 'wellbeing', 'Other-than-permanent male employees covered by accident insurance', 'count', 'number', false, 1360, 'Template cell HR!D109'),
('hr.wellbeing_oth_emp_m_parental', 'HR', 'wellbeing', 'Other-than-permanent male employees covered by maternity/paternity benefits', 'count', 'number', false, 1370, 'Template cell HR!E109'),
('hr.wellbeing_oth_emp_m_daycare', 'HR', 'wellbeing', 'Other-than-permanent male employees covered by daycare facilities', 'count', 'number', false, 1380, 'Template cell HR!F109'),
('hr.wellbeing_oth_emp_f_health', 'HR', 'wellbeing', 'Other-than-permanent female employees covered by health insurance', 'count', 'number', false, 1390, 'Template cell HR!C110'),
('hr.wellbeing_oth_emp_f_accident', 'HR', 'wellbeing', 'Other-than-permanent female employees covered by accident insurance', 'count', 'number', false, 1400, 'Template cell HR!D110'),
('hr.wellbeing_oth_emp_f_parental', 'HR', 'wellbeing', 'Other-than-permanent female employees covered by maternity/paternity benefits', 'count', 'number', false, 1410, 'Template cell HR!E110'),
('hr.wellbeing_oth_emp_f_daycare', 'HR', 'wellbeing', 'Other-than-permanent female employees covered by daycare facilities', 'count', 'number', false, 1420, 'Template cell HR!F110'),
('hr.wellbeing_perm_wkr_m_health', 'HR', 'wellbeing', 'Permanent male workers covered by health insurance', 'count', 'number', false, 1430, 'Template cell HR!C112'),
('hr.wellbeing_perm_wkr_m_accident', 'HR', 'wellbeing', 'Permanent male workers covered by accident insurance', 'count', 'number', false, 1440, 'Template cell HR!D112'),
('hr.wellbeing_perm_wkr_m_parental', 'HR', 'wellbeing', 'Permanent male workers covered by maternity/paternity benefits', 'count', 'number', false, 1450, 'Template cell HR!E112'),
('hr.wellbeing_perm_wkr_m_daycare', 'HR', 'wellbeing', 'Permanent male workers covered by daycare facilities', 'count', 'number', false, 1460, 'Template cell HR!F112'),
('hr.wellbeing_perm_wkr_f_health', 'HR', 'wellbeing', 'Permanent female workers covered by health insurance', 'count', 'number', false, 1470, 'Template cell HR!C113'),
('hr.wellbeing_perm_wkr_f_accident', 'HR', 'wellbeing', 'Permanent female workers covered by accident insurance', 'count', 'number', false, 1480, 'Template cell HR!D113'),
('hr.wellbeing_perm_wkr_f_parental', 'HR', 'wellbeing', 'Permanent female workers covered by maternity/paternity benefits', 'count', 'number', false, 1490, 'Template cell HR!E113'),
('hr.wellbeing_perm_wkr_f_daycare', 'HR', 'wellbeing', 'Permanent female workers covered by daycare facilities', 'count', 'number', false, 1500, 'Template cell HR!F113'),
('hr.wellbeing_oth_wkr_m_health', 'HR', 'wellbeing', 'Other-than-permanent male workers covered by health insurance', 'count', 'number', false, 1510, 'Template cell HR!C115'),
('hr.wellbeing_oth_wkr_m_accident', 'HR', 'wellbeing', 'Other-than-permanent male workers covered by accident insurance', 'count', 'number', false, 1520, 'Template cell HR!D115'),
('hr.wellbeing_oth_wkr_m_parental', 'HR', 'wellbeing', 'Other-than-permanent male workers covered by maternity/paternity benefits', 'count', 'number', false, 1530, 'Template cell HR!E115'),
('hr.wellbeing_oth_wkr_m_daycare', 'HR', 'wellbeing', 'Other-than-permanent male workers covered by daycare facilities', 'count', 'number', false, 1540, 'Template cell HR!F115'),
('hr.wellbeing_oth_wkr_f_health', 'HR', 'wellbeing', 'Other-than-permanent female workers covered by health insurance', 'count', 'number', false, 1550, 'Template cell HR!C116'),
('hr.wellbeing_oth_wkr_f_accident', 'HR', 'wellbeing', 'Other-than-permanent female workers covered by accident insurance', 'count', 'number', false, 1560, 'Template cell HR!D116'),
('hr.wellbeing_oth_wkr_f_parental', 'HR', 'wellbeing', 'Other-than-permanent female workers covered by maternity/paternity benefits', 'count', 'number', false, 1570, 'Template cell HR!E116'),
('hr.wellbeing_oth_wkr_f_daycare', 'HR', 'wellbeing', 'Other-than-permanent female workers covered by daycare facilities', 'count', 'number', false, 1580, 'Template cell HR!F116'),
('hr.matleave_emp_entitled_m', 'HR', 'matleave_emp', 'Male employees entitled to parental leave', 'count', 'number', false, 1590, 'Template cell HR!D121'),
('hr.matleave_emp_entitled_f', 'HR', 'matleave_emp', 'Female employees entitled to parental leave', 'count', 'number', false, 1600, 'Template cell HR!E121'),
('hr.matleave_emp_availed_m', 'HR', 'matleave_emp', 'Male employees who availed parental leave', 'count', 'number', false, 1610, 'Template cell HR!D122'),
('hr.matleave_emp_availed_f', 'HR', 'matleave_emp', 'Female employees who availed parental leave', 'count', 'number', false, 1620, 'Template cell HR!E122'),
('hr.matleave_emp_returned_m', 'HR', 'matleave_emp', 'Male employees who returned to work after parental leave', 'count', 'number', false, 1630, 'Template cell HR!D123'),
('hr.matleave_emp_returned_f', 'HR', 'matleave_emp', 'Female employees who returned to work after parental leave', 'count', 'number', false, 1640, 'Template cell HR!E123'),
('hr.matleave_emp_due_return_m', 'HR', 'matleave_emp', 'Male employees due to return after parental leave', 'count', 'number', false, 1650, 'Template cell HR!D124'),
('hr.matleave_emp_due_return_f', 'HR', 'matleave_emp', 'Female employees due to return after parental leave', 'count', 'number', false, 1660, 'Template cell HR!E124'),
('hr.matleave_emp_retained_12m_m', 'HR', 'matleave_emp', 'Male employees still employed 12 months after parental leave', 'count', 'number', false, 1670, 'Template cell HR!D125'),
('hr.matleave_emp_retained_12m_f', 'HR', 'matleave_emp', 'Female employees still employed 12 months after parental leave', 'count', 'number', false, 1680, 'Template cell HR!E125'),
('hr.matleave_emp_returned_prior_m', 'HR', 'matleave_emp', 'Male employees who returned from parental leave in the prior period', 'count', 'number', false, 1690, 'Template cell HR!D126'),
('hr.matleave_emp_returned_prior_f', 'HR', 'matleave_emp', 'Female employees who returned from parental leave in the prior period', 'count', 'number', false, 1700, 'Template cell HR!E126'),
('hr.matleave_wkr_entitled_m', 'HR', 'matleave_wkr', 'Male workers entitled to parental leave', 'count', 'number', false, 1710, 'Template cell HR!D133'),
('hr.matleave_wkr_entitled_f', 'HR', 'matleave_wkr', 'Female workers entitled to parental leave', 'count', 'number', false, 1720, 'Template cell HR!E133'),
('hr.matleave_wkr_availed_m', 'HR', 'matleave_wkr', 'Male workers who availed parental leave', 'count', 'number', false, 1730, 'Template cell HR!D134'),
('hr.matleave_wkr_availed_f', 'HR', 'matleave_wkr', 'Female workers who availed parental leave', 'count', 'number', false, 1740, 'Template cell HR!E134'),
('hr.matleave_wkr_returned_m', 'HR', 'matleave_wkr', 'Male workers who returned to work after parental leave', 'count', 'number', false, 1750, 'Template cell HR!D135'),
('hr.matleave_wkr_returned_f', 'HR', 'matleave_wkr', 'Female workers who returned to work after parental leave', 'count', 'number', false, 1760, 'Template cell HR!E135'),
('hr.matleave_wkr_due_return_m', 'HR', 'matleave_wkr', 'Male workers due to return after parental leave', 'count', 'number', false, 1770, 'Template cell HR!D136'),
('hr.matleave_wkr_due_return_f', 'HR', 'matleave_wkr', 'Female workers due to return after parental leave', 'count', 'number', false, 1780, 'Template cell HR!E136'),
('hr.matleave_wkr_retained_12m_m', 'HR', 'matleave_wkr', 'Male workers still employed 12 months after parental leave', 'count', 'number', false, 1790, 'Template cell HR!D137'),
('hr.matleave_wkr_retained_12m_f', 'HR', 'matleave_wkr', 'Female workers still employed 12 months after parental leave', 'count', 'number', false, 1800, 'Template cell HR!E137'),
('hr.matleave_wkr_returned_prior_m', 'HR', 'matleave_wkr', 'Male workers who returned from parental leave in the prior period', 'count', 'number', false, 1810, 'Template cell HR!D138'),
('hr.matleave_wkr_returned_prior_f', 'HR', 'matleave_wkr', 'Female workers who returned from parental leave in the prior period', 'count', 'number', false, 1820, 'Template cell HR!E138'),
('hr.wellbeing_spend_text', 'HR', 'wellbeing_spend', 'Spend on well-being measures (Cr. INR)', null, 'text', false, 1830, 'Template cell HR!C144'),
('hr.retirement_pf_emp', 'HR', 'retirement', 'Employees covered by PF', 'count', 'number', false, 1840, 'Template cell HR!C149'),
('hr.retirement_pf_wkr', 'HR', 'retirement', 'Workers covered by PF', 'count', 'number', false, 1850, 'Template cell HR!D149'),
('hr.retirement_pf_deposited', 'HR', 'retirement', 'PF: deducted and deposited with the authority', 'count', 'number', false, 1860, 'Template cell HR!E149'),
('hr.retirement_gratuity_emp', 'HR', 'retirement', 'Employees covered by Gratuity', 'count', 'number', false, 1870, 'Template cell HR!C150'),
('hr.retirement_gratuity_wkr', 'HR', 'retirement', 'Workers covered by Gratuity', 'count', 'number', false, 1880, 'Template cell HR!D150'),
('hr.retirement_gratuity_deposited', 'HR', 'retirement', 'Gratuity: deducted and deposited with the authority', 'count', 'number', false, 1890, 'Template cell HR!E150'),
('hr.retirement_esi_emp', 'HR', 'retirement', 'Employees covered by ESI', 'count', 'number', false, 1900, 'Template cell HR!C151'),
('hr.retirement_esi_wkr', 'HR', 'retirement', 'Workers covered by ESI', 'count', 'number', false, 1910, 'Template cell HR!D151'),
('hr.retirement_esi_deposited', 'HR', 'retirement', 'ESI: deducted and deposited with the authority', 'count', 'number', false, 1920, 'Template cell HR!E151'),
('hr.retirement_other_emp', 'HR', 'retirement', 'Employees covered by Others', 'count', 'number', false, 1930, 'Template cell HR!C152'),
('hr.retirement_other_wkr', 'HR', 'retirement', 'Workers covered by Others', 'count', 'number', false, 1940, 'Template cell HR!D152'),
('hr.retirement_other_deposited', 'HR', 'retirement', 'Others: deducted and deposited with the authority', 'count', 'number', false, 1950, 'Template cell HR!E152'),
('hr.perf_review_emp_m', 'HR', 'perf_review', 'Male employees receiving performance reviews', 'count', 'number', false, 1960, 'Template cell HR!C159'),
('hr.perf_review_emp_f', 'HR', 'perf_review', 'Female employees receiving performance reviews', 'count', 'number', false, 1970, 'Template cell HR!C160'),
('hr.perf_review_wkr_m', 'HR', 'perf_review', 'Male workers receiving performance reviews', 'count', 'number', false, 1980, 'Template cell HR!C163'),
('hr.perf_review_wkr_f', 'HR', 'perf_review', 'Female workers receiving performance reviews', 'count', 'number', false, 1990, 'Template cell HR!C164'),
('hr.perf_review_wkr_total', 'HR', 'perf_review', 'Total workers receiving performance reviews', 'count', 'number', false, 2000, 'Template cell HR!C165'),
('hr.complaints_posh_filed', 'HR', 'complaints', 'Complaints filed during the year: sexual harassment (POSH)', 'count', 'number', false, 2010, 'Template cell HR!C170'),
('hr.complaints_posh_pending', 'HR', 'complaints', 'Complaints pending at year end: sexual harassment (POSH)', 'count', 'number', false, 2020, 'Template cell HR!D170'),
('hr.complaints_posh_remarks', 'HR', 'complaints', 'Remarks on complaints: sexual harassment (POSH)', null, 'text', false, 2030, 'Template cell HR!E170'),
('hr.complaints_discrimination_filed', 'HR', 'complaints', 'Complaints filed during the year: discrimination at workplace', 'count', 'number', false, 2040, 'Template cell HR!C171'),
('hr.complaints_discrimination_pending', 'HR', 'complaints', 'Complaints pending at year end: discrimination at workplace', 'count', 'number', false, 2050, 'Template cell HR!D171'),
('hr.complaints_discrimination_remarks', 'HR', 'complaints', 'Remarks on complaints: discrimination at workplace', null, 'text', false, 2060, 'Template cell HR!E171'),
('hr.complaints_child_labour_filed', 'HR', 'complaints', 'Complaints filed during the year: child labour', 'count', 'number', false, 2070, 'Template cell HR!C172'),
('hr.complaints_child_labour_pending', 'HR', 'complaints', 'Complaints pending at year end: child labour', 'count', 'number', false, 2080, 'Template cell HR!D172'),
('hr.complaints_child_labour_remarks', 'HR', 'complaints', 'Remarks on complaints: child labour', null, 'text', false, 2090, 'Template cell HR!E172'),
('hr.complaints_forced_labour_filed', 'HR', 'complaints', 'Complaints filed during the year: forced/involuntary labour', 'count', 'number', false, 2100, 'Template cell HR!C173'),
('hr.complaints_forced_labour_pending', 'HR', 'complaints', 'Complaints pending at year end: forced/involuntary labour', 'count', 'number', false, 2110, 'Template cell HR!D173'),
('hr.complaints_forced_labour_remarks', 'HR', 'complaints', 'Remarks on complaints: forced/involuntary labour', null, 'text', false, 2120, 'Template cell HR!E173'),
('hr.complaints_wages_filed', 'HR', 'complaints', 'Complaints filed during the year: wages', 'count', 'number', false, 2130, 'Template cell HR!C174'),
('hr.complaints_wages_pending', 'HR', 'complaints', 'Complaints pending at year end: wages', 'count', 'number', false, 2140, 'Template cell HR!D174'),
('hr.complaints_wages_remarks', 'HR', 'complaints', 'Remarks on complaints: wages', null, 'text', false, 2150, 'Template cell HR!E174'),
('hr.complaints_other_filed', 'HR', 'complaints', 'Complaints filed during the year: other human-rights issues', 'count', 'number', false, 2160, 'Template cell HR!C175'),
('hr.complaints_other_pending', 'HR', 'complaints', 'Complaints pending at year end: other human-rights issues', 'count', 'number', false, 2170, 'Template cell HR!D175'),
('hr.complaints_other_remarks', 'HR', 'complaints', 'Remarks on complaints: other human-rights issues', null, 'text', false, 2180, 'Template cell HR!E175'),
('hr.discrimination_reviewed_status', 'HR', 'discrimination', 'Discrimination: incidents reviewed (status)', 'count', 'number', false, 2190, 'Template cell HR!C179'),
('hr.discrimination_reviewed_action', 'HR', 'discrimination', 'Discrimination: incidents reviewed (actions taken)', 'count', 'number', false, 2200, 'Template cell HR!D179'),
('hr.discrimination_remediation_wip_status', 'HR', 'discrimination', 'Discrimination: remediation plans being implemented (status)', 'count', 'number', false, 2210, 'Template cell HR!C180'),
('hr.discrimination_remediation_wip_action', 'HR', 'discrimination', 'Discrimination: remediation plans being implemented (actions taken)', 'count', 'number', false, 2220, 'Template cell HR!D180'),
('hr.discrimination_remediation_done_status', 'HR', 'discrimination', 'Discrimination: remediation plans implemented and reviewed (status)', 'count', 'number', false, 2230, 'Template cell HR!C181'),
('hr.discrimination_remediation_done_action', 'HR', 'discrimination', 'Discrimination: remediation plans implemented and reviewed (actions taken)', 'count', 'number', false, 2240, 'Template cell HR!D181'),
('hr.discrimination_closed_status', 'HR', 'discrimination', 'Discrimination: incidents no longer subject to action (status)', 'count', 'number', false, 2250, 'Template cell HR!C182'),
('hr.discrimination_closed_action', 'HR', 'discrimination', 'Discrimination: incidents no longer subject to action (actions taken)', 'count', 'number', false, 2260, 'Template cell HR!D182'),
('hr.minwage_perm_emp_m_equal', 'HR', 'minwage', 'Paid equal to minimum wage: permanent male employees', 'count', 'number', false, 2270, 'Template cell HR!C190'),
('hr.minwage_perm_emp_m_above', 'HR', 'minwage', 'Paid above minimum wage: permanent male employees', 'count', 'number', false, 2280, 'Template cell HR!D190'),
('hr.minwage_perm_emp_f_equal', 'HR', 'minwage', 'Paid equal to minimum wage: permanent female employees', 'count', 'number', false, 2290, 'Template cell HR!C191'),
('hr.minwage_perm_emp_f_above', 'HR', 'minwage', 'Paid above minimum wage: permanent female employees', 'count', 'number', false, 2300, 'Template cell HR!D191'),
('hr.minwage_oth_emp_m_equal', 'HR', 'minwage', 'Paid equal to minimum wage: other-than-permanent male employees', 'count', 'number', false, 2310, 'Template cell HR!C193'),
('hr.minwage_oth_emp_m_above', 'HR', 'minwage', 'Paid above minimum wage: other-than-permanent male employees', 'count', 'number', false, 2320, 'Template cell HR!D193'),
('hr.minwage_oth_emp_f_equal', 'HR', 'minwage', 'Paid equal to minimum wage: other-than-permanent female employees', 'count', 'number', false, 2330, 'Template cell HR!C194'),
('hr.minwage_oth_emp_f_above', 'HR', 'minwage', 'Paid above minimum wage: other-than-permanent female employees', 'count', 'number', false, 2340, 'Template cell HR!D194'),
('hr.minwage_perm_wkr_m_equal', 'HR', 'minwage', 'Paid equal to minimum wage: permanent male workers', 'count', 'number', false, 2350, 'Template cell HR!C197'),
('hr.minwage_perm_wkr_m_above', 'HR', 'minwage', 'Paid above minimum wage: permanent male workers', 'count', 'number', false, 2360, 'Template cell HR!D197'),
('hr.minwage_perm_wkr_f_equal', 'HR', 'minwage', 'Paid equal to minimum wage: permanent female workers', 'count', 'number', false, 2370, 'Template cell HR!C198'),
('hr.minwage_perm_wkr_f_above', 'HR', 'minwage', 'Paid above minimum wage: permanent female workers', 'count', 'number', false, 2380, 'Template cell HR!D198'),
('hr.minwage_oth_wkr_m_equal', 'HR', 'minwage', 'Paid equal to minimum wage: other-than-permanent male workers', 'count', 'number', false, 2390, 'Template cell HR!C200'),
('hr.minwage_oth_wkr_m_above', 'HR', 'minwage', 'Paid above minimum wage: other-than-permanent male workers', 'count', 'number', false, 2400, 'Template cell HR!D200'),
('hr.minwage_oth_wkr_f_equal', 'HR', 'minwage', 'Paid equal to minimum wage: other-than-permanent female workers', 'count', 'number', false, 2410, 'Template cell HR!C201'),
('hr.minwage_oth_wkr_f_above', 'HR', 'minwage', 'Paid above minimum wage: other-than-permanent female workers', 'count', 'number', false, 2420, 'Template cell HR!D201'),
('hr.wages_rural_paid', 'HR', 'wages_location', 'Wages paid: Rural locations', 'INR', 'number', false, 2430, 'Template cell HR!C207'),
('hr.wages_rural_total', 'HR', 'wages_location', 'Total wage cost: Rural locations', 'INR', 'number', false, 2440, 'Template cell HR!D207'),
('hr.wages_semiurban_paid', 'HR', 'wages_location', 'Wages paid: Semi-urban locations', 'INR', 'number', false, 2450, 'Template cell HR!C208'),
('hr.wages_semiurban_total', 'HR', 'wages_location', 'Total wage cost: Semi-urban locations', 'INR', 'number', false, 2460, 'Template cell HR!D208'),
('hr.wages_urban_paid', 'HR', 'wages_location', 'Wages paid: urban locations', 'INR', 'number', false, 2470, 'Template cell HR!C209'),
('hr.wages_urban_total', 'HR', 'wages_location', 'Total wage cost: urban locations', 'INR', 'number', false, 2480, 'Template cell HR!D209'),
('hr.wages_metro_paid', 'HR', 'wages_location', 'Wages paid: Metropolitan locations', 'INR', 'number', false, 2490, 'Template cell HR!C210'),
('hr.wages_metro_total', 'HR', 'wages_location', 'Total wage cost: Metropolitan locations', 'INR', 'number', false, 2500, 'Template cell HR!D210'),
('hr.security_total', 'HR', 'security', 'Security personnel in the organisation', 'count', 'number', false, 2510, 'Template cell HR!C215'),
('hr.security_trained', 'HR', 'security', 'Security personnel formally trained on human rights', 'count', 'number', false, 2520, 'Template cell HR!C216'),
('hr.security_thirdparty_text', 'HR', 'security', 'Whether training requirements extend to third-party security', null, 'text', false, 2530, 'Template cell HR!C218')
on conflict (key) do update set
    domain = excluded.domain,
    section = excluded.section,
    label = excluded.label,
    unit = excluded.unit,
    value_type = excluded.value_type,
    is_memo = excluded.is_memo,
    sort_order = excluded.sort_order,
    notes = excluded.notes;

-- -----------------------------------------------------------------------------
-- BRSR - Procurement (sheet "Proc,Supply Chain, MKt") — 71 parameters
-- -----------------------------------------------------------------------------
insert into esg.input_parameter (key, domain, section, label, unit, value_type, is_memo, sort_order, notes) values
('proc.recycled_input_1_name', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 1: name', null, 'text', false, 10, 'Template cell Proc,Supply Chain, MKt!B5'),
('proc.recycled_input_1_pct', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 1: % of total material', 'fraction', 'number', false, 20, 'Template cell Proc,Supply Chain, MKt!C5'),
('proc.recycled_input_2_name', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 2: name', null, 'text', false, 30, 'List slot 2 beyond the template''s placeholder rows: ingested and chartable, but the export has no cell for it'),
('proc.recycled_input_2_pct', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 2: % of total material', 'fraction', 'number', false, 40, 'List slot 2 beyond the template''s placeholder rows: ingested and chartable, but the export has no cell for it'),
('proc.recycled_input_3_name', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 3: name', null, 'text', false, 50, 'List slot 3 beyond the template''s placeholder rows: ingested and chartable, but the export has no cell for it'),
('proc.recycled_input_3_pct', 'PROCUREMENT', 'recycled_pct', 'Recycled/reused input material 3: % of total material', 'fraction', 'number', false, 60, 'List slot 3 beyond the template''s placeholder rows: ingested and chartable, but the export has no cell for it'),
('proc.material_nonrenew_1_name', 'PROCUREMENT', 'mat_nonrenew', 'Non-renewable material 1: name', null, 'text', false, 70, 'Template cell Proc,Supply Chain, MKt!B10'),
('proc.material_nonrenew_1_qty', 'PROCUREMENT', 'mat_nonrenew', 'Non-renewable material 1: quantity', 'MT', 'number', false, 80, 'Template cell Proc,Supply Chain, MKt!D10'),
('proc.material_nonrenew_2_name', 'PROCUREMENT', 'mat_nonrenew', 'Non-renewable material 2: name', null, 'text', false, 90, 'Template cell Proc,Supply Chain, MKt!B11'),
('proc.material_nonrenew_2_qty', 'PROCUREMENT', 'mat_nonrenew', 'Non-renewable material 2: quantity', 'MT', 'number', false, 100, 'Template cell Proc,Supply Chain, MKt!D11'),
('proc.material_renew_1_name', 'PROCUREMENT', 'mat_renew', 'Renewable material 1: name', null, 'text', false, 110, 'Template cell Proc,Supply Chain, MKt!B13'),
('proc.material_renew_1_qty', 'PROCUREMENT', 'mat_renew', 'Renewable material 1: quantity', 'MT', 'number', false, 120, 'Template cell Proc,Supply Chain, MKt!D13'),
('proc.material_renew_2_name', 'PROCUREMENT', 'mat_renew', 'Renewable material 2: name', null, 'text', false, 130, 'Template cell Proc,Supply Chain, MKt!B14'),
('proc.material_renew_2_qty', 'PROCUREMENT', 'mat_renew', 'Renewable material 2: quantity', 'MT', 'number', false, 140, 'Template cell Proc,Supply Chain, MKt!D14'),
('proc.total_input_mt', 'PROCUREMENT', 'recycled_input', 'Total input material', 'MT', 'number', false, 150, 'Template cell Proc,Supply Chain, MKt!D20'),
('proc.recycled_input_mt', 'PROCUREMENT', 'recycled_input', 'Recycled input material used', 'MT', 'number', false, 160, 'Template cell Proc,Supply Chain, MKt!D21'),
('proc.reclaimed_products', 'PROCUREMENT', 'reclaimed', 'Products and packaging reclaimed', 'MT', 'number', false, 170, 'Template cell Proc,Supply Chain, MKt!D26'),
('proc.reclaimed_products_sold', 'PROCUREMENT', 'reclaimed', 'Products and packaging sold', 'MT', 'number', false, 180, 'Template cell Proc,Supply Chain, MKt!D27'),
('proc.msme_share', 'PROCUREMENT', 'sourcing', 'Input material sourced directly from MSMEs/small producers (share by value)', 'fraction', 'number', false, 190, 'Template cell Proc,Supply Chain, MKt!C41'),
('proc.india_share', 'PROCUREMENT', 'sourcing', 'Input material sourced directly from within India (share by value)', 'fraction', 'number', false, 200, 'Template cell Proc,Supply Chain, MKt!C42'),
('proc.budget_total_text', 'PROCUREMENT', 'local_spend', 'Total procurement budget', null, 'text', false, 210, 'Template cell Proc,Supply Chain, MKt!C47'),
('proc.budget_local_text', 'PROCUREMENT', 'local_spend', 'Procurement budget spent on local suppliers', null, 'text', false, 220, 'Template cell Proc,Supply Chain, MKt!C48'),
('proc.pref_policy_text', 'PROCUREMENT', 'preferential', 'Preferential procurement policy in place', null, 'text', false, 230, 'Template cell Proc,Supply Chain, MKt!C52'),
('proc.pref_groups_text', 'PROCUREMENT', 'preferential', 'Marginalised/vulnerable groups procured from', null, 'text', false, 240, 'Template cell Proc,Supply Chain, MKt!C53'),
('proc.pref_share_text', 'PROCUREMENT', 'preferential', 'Share of total procurement from marginalised/vulnerable groups', null, 'text', false, 250, 'Template cell Proc,Supply Chain, MKt!C54'),
('proc.consumer_grievance_text', 'PROCUREMENT', 'grievance', 'Mechanisms to receive and respond to consumer complaints', null, 'text', false, 260, 'Template cell Proc,Supply Chain, MKt!C56'),
('proc.turnover_env_pct', 'PROCUREMENT', 'turnover_info', 'Turnover share: environmental and social parameters disclosed', 'fraction', 'number', false, 270, 'Template cell Proc,Supply Chain, MKt!C60'),
('proc.turnover_safety_pct', 'PROCUREMENT', 'turnover_info', 'Turnover share: safe and responsible usage disclosed', 'fraction', 'number', false, 280, 'Template cell Proc,Supply Chain, MKt!C61'),
('proc.turnover_recycling_pct', 'PROCUREMENT', 'turnover_info', 'Turnover share: recycling/safe disposal disclosed', 'fraction', 'number', false, 290, 'Template cell Proc,Supply Chain, MKt!C62'),
('proc.consumer_education_text', 'PROCUREMENT', 'consumer_edu', 'Steps taken to inform and educate consumers', null, 'text', false, 300, 'Template cell Proc,Supply Chain, MKt!C64'),
('proc.vcp_awareness_count', 'PROCUREMENT', 'vcp_awareness', 'Awareness programmes held for value-chain partners', 'count', 'number', false, 310, 'Template cell Proc,Supply Chain, MKt!B70'),
('proc.vcp_awareness_topics', 'PROCUREMENT', 'vcp_awareness', 'Topics/principles covered in value-chain awareness programmes', null, 'text', false, 320, 'Template cell Proc,Supply Chain, MKt!C70'),
('proc.vcp_awareness_coverage', 'PROCUREMENT', 'vcp_awareness', 'Value-chain partners covered by awareness programmes (share by value)', 'fraction', 'number', false, 330, 'Template cell Proc,Supply Chain, MKt!D70'),
('proc.vcp_assess_safety', 'PROCUREMENT', 'vcp_assess_safety', 'Value-chain partners assessed: health and safety practices', 'fraction', 'number', false, 340, 'Template cell Proc,Supply Chain, MKt!C75'),
('proc.vcp_assess_conditions', 'PROCUREMENT', 'vcp_assess_safety', 'Value-chain partners assessed: working conditions', 'fraction', 'number', false, 350, 'Template cell Proc,Supply Chain, MKt!C76'),
('proc.vcp_corrective_safety_text', 'PROCUREMENT', 'vcp_corrective_safety', 'Corrective actions from value-chain safety assessments', null, 'text', false, 360, 'Template cell Proc,Supply Chain, MKt!C78'),
('proc.vcp_assess_posh', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: sexual harassment', 'fraction', 'number', false, 370, 'Template cell Proc,Supply Chain, MKt!C82'),
('proc.vcp_assess_discrimination', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: discrimination at workplace', 'fraction', 'number', false, 380, 'Template cell Proc,Supply Chain, MKt!C83'),
('proc.vcp_assess_child_labour', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: child labour', 'fraction', 'number', false, 390, 'Template cell Proc,Supply Chain, MKt!C84'),
('proc.vcp_assess_forced_labour', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: forced/involuntary labour', 'fraction', 'number', false, 400, 'Template cell Proc,Supply Chain, MKt!C85'),
('proc.vcp_assess_wages', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: wages', 'fraction', 'number', false, 410, 'Template cell Proc,Supply Chain, MKt!C86'),
('proc.vcp_assess_other', 'PROCUREMENT', 'vcp_assess_social', 'Value-chain partners assessed: other', 'fraction', 'number', false, 420, 'Template cell Proc,Supply Chain, MKt!C87'),
('proc.vcp_corrective_social_text', 'PROCUREMENT', 'vcp_corrective_social', 'Corrective actions from value-chain social assessments', null, 'text', false, 430, 'Template cell Proc,Supply Chain, MKt!C89'),
('proc.value_chain_env_impact_text', 'PROCUREMENT', 'value_chain_impact', 'Significant adverse environmental impact from the value chain', null, 'text', false, 440, 'Template cell Proc,Supply Chain, MKt!C92'),
('proc.suppliers_env_assessed', 'PROCUREMENT', 'env_impacts', 'Suppliers assessed for environmental impacts', 'count', 'number', false, 450, 'Template cell Proc,Supply Chain, MKt!D95'),
('proc.suppliers_env_negative', 'PROCUREMENT', 'env_impacts', 'Suppliers with significant negative environmental impacts', 'count', 'number', false, 460, 'Template cell Proc,Supply Chain, MKt!D96'),
('proc.suppliers_env_improved', 'PROCUREMENT', 'env_impacts', 'Suppliers with negative environmental impacts where improvements were agreed', 'count', 'number', false, 470, 'Template cell Proc,Supply Chain, MKt!D97'),
('proc.suppliers_env_terminated', 'PROCUREMENT', 'env_impacts', 'Suppliers terminated for negative environmental impacts', 'count', 'number', false, 480, 'Template cell Proc,Supply Chain, MKt!D99'),
('proc.child_labour_risk_ops', 'PROCUREMENT', 'child_labour_risk', 'Operations/suppliers at significant risk: child labour', 'count', 'number', false, 490, 'Template cell Proc,Supply Chain, MKt!C106'),
('proc.young_workers_risk_ops', 'PROCUREMENT', 'child_labour_risk', 'Operations/suppliers at significant risk: young workers in hazardous work', 'count', 'number', false, 500, 'Template cell Proc,Supply Chain, MKt!C107'),
('proc.child_labour_risk_optype_text', 'PROCUREMENT', 'child_labour_detail', 'Operations/suppliers at child-labour risk: type of operation', null, 'text', false, 510, 'Template cell Proc,Supply Chain, MKt!C111'),
('proc.child_labour_risk_geo_text', 'PROCUREMENT', 'child_labour_detail', 'Operations/suppliers at child-labour risk: geography', null, 'text', false, 520, 'Template cell Proc,Supply Chain, MKt!C112'),
('proc.child_labour_measures_text', 'PROCUREMENT', 'child_labour_measures', 'Measures taken to abolish child labour', null, 'text', false, 530, 'Template cell Proc,Supply Chain, MKt!C115'),
('proc.suppliers_social_assessed', 'PROCUREMENT', 'social_impacts', 'Suppliers assessed for social impacts', 'count', 'number', false, 540, 'Template cell Proc,Supply Chain, MKt!D119'),
('proc.suppliers_social_negative', 'PROCUREMENT', 'social_impacts', 'Suppliers with significant negative social impacts', 'count', 'number', false, 550, 'Template cell Proc,Supply Chain, MKt!D120'),
('proc.social_impacts_identified', 'PROCUREMENT', 'social_impacts', 'Significant negative social impacts identified in the supply chain', 'count', 'number', false, 560, 'Template cell Proc,Supply Chain, MKt!D121'),
('proc.suppliers_social_improved', 'PROCUREMENT', 'social_impacts', 'Suppliers with negative social impacts where improvements were agreed', 'count', 'number', false, 570, 'Template cell Proc,Supply Chain, MKt!D123'),
('proc.inputs_total_wt', 'PROCUREMENT', 'sustainable_inputs', 'Total inputs by weight', 'MT', 'number', false, 580, 'Template cell Proc,Supply Chain, MKt!B128'),
('proc.inputs_sustainable_wt', 'PROCUREMENT', 'sustainable_inputs', 'Inputs sourced sustainably by weight', 'MT', 'number', false, 590, 'Template cell Proc,Supply Chain, MKt!C128'),
('proc.eol_plastics_reused', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Plastics(including packaging): re-used', 'MT', 'number', false, 600, 'Template cell Proc,Supply Chain, MKt!C33'),
('proc.eol_plastics_recycled', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Plastics(including packaging): recycled', 'MT', 'number', false, 610, 'Template cell Proc,Supply Chain, MKt!D33'),
('proc.eol_plastics_disposed', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Plastics(including packaging): safely disposed', 'MT', 'number', false, 620, 'Template cell Proc,Supply Chain, MKt!E33'),
('proc.eol_ewaste_reused', 'PROCUREMENT', 'eol_reclaim', 'End-of-life E-waste: re-used', 'MT', 'number', false, 630, 'Template cell Proc,Supply Chain, MKt!C34'),
('proc.eol_ewaste_recycled', 'PROCUREMENT', 'eol_reclaim', 'End-of-life E-waste: recycled', 'MT', 'number', false, 640, 'Template cell Proc,Supply Chain, MKt!D34'),
('proc.eol_ewaste_disposed', 'PROCUREMENT', 'eol_reclaim', 'End-of-life E-waste: safely disposed', 'MT', 'number', false, 650, 'Template cell Proc,Supply Chain, MKt!E34'),
('proc.eol_hazardous_reused', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Hazardous Waste: re-used', 'MT', 'number', false, 660, 'Template cell Proc,Supply Chain, MKt!C35'),
('proc.eol_hazardous_recycled', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Hazardous Waste: recycled', 'MT', 'number', false, 670, 'Template cell Proc,Supply Chain, MKt!D35'),
('proc.eol_hazardous_disposed', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Hazardous Waste: safely disposed', 'MT', 'number', false, 680, 'Template cell Proc,Supply Chain, MKt!E35'),
('proc.eol_other_reused', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Other Waste: re-used', 'MT', 'number', false, 690, 'Template cell Proc,Supply Chain, MKt!C36'),
('proc.eol_other_recycled', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Other Waste: recycled', 'MT', 'number', false, 700, 'Template cell Proc,Supply Chain, MKt!D36'),
('proc.eol_other_disposed', 'PROCUREMENT', 'eol_reclaim', 'End-of-life Other Waste: safely disposed', 'MT', 'number', false, 710, 'Template cell Proc,Supply Chain, MKt!E36')
on conflict (key) do update set
    domain = excluded.domain,
    section = excluded.section,
    label = excluded.label,
    unit = excluded.unit,
    value_type = excluded.value_type,
    is_memo = excluded.is_memo,
    sort_order = excluded.sort_order,
    notes = excluded.notes;

notify pgrst, 'reload schema';
